# Generated by Django 5.2 on 2025-04-21 23:49

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0002_alter_register_attendance_alter_register_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El año escolar no puede ser menor a 1.'), django.core.validators.MaxValueValidator(4, message='El año escolar no puede ser mayor a 4.')]),
        ),
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_subject', to='academico_app.professor'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='El año escolar no puede ser menor a 1.'), django.core.validators.MaxValueValidator(4, message='El año escolar no puede ser mayor a 4.')]),
        ),
    ]
