# Generated by Django 5.2 on 2025-04-27 18:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0003_alter_student_academic_year_alter_subject_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='grade',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
