# Generated by Django 5.2 on 2025-05-18 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0004_alter_register_grade_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academico_app.subject'),
        ),
    ]
