# Generated by Django 5.2 on 2025-05-25 22:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0006_alter_comment_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_attendance', to='academico_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_attendance', to='academico_app.subject')),
            ],
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(5)])),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_register', to='academico_app.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_register', to='academico_app.subject')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_attendance_student_subject_date'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'date'), name='unique_grade_student_subject_date'),
        ),
        migrations.AddConstraint(
            model_name='graderecord',
            constraint=models.CheckConstraint(condition=models.Q(('grade__range', (0, 5))), name='valid_grade'),
        ),
    ]
