# Generated by Django 5.2 on 2025-05-26 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0007_subject_completed_attendancerecord_graderecord_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='unique_attendance_student_subject_date',
        ),
    ]
