# Generated by Django 5.2 on 2025-05-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0008_remove_attendancerecord_unique_attendance_student_subject_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='graderecord',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
