# Generated by Django 5.2 on 2025-05-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0009_graderecord_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graderecord',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
