# Generated by Django 5.2 on 2025-05-28 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico_app', '0010_alter_graderecord_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='graderecord',
            name='unique_grade_student_subject_date',
        ),
    ]
